Module.loader.loadModules([
"net.xp.util.array._All",
"net.xp.util.Debuggable",
"net.xp.util.dom._All",
"net.xp.util.function._All",
"net.xp.util.InstanceStatusManager",
"net.xp.util.object._All",
"net.xp.util.string._All",
"net.xp.util.Times",
"net.xp.prototype.str.URL",
"net.xp.util.xml._All"]);