new Module("net.xp._All",[
"net.xp.algorithm._All",
"net.xp.app._All",
"net.xp.base._All",
"net.xp.browser._All",
"net.xp.control._All",
"net.xp.core._All",
"net.xp.data._All",
"net.xp.dom._All",
"net.xp.effect._All",
"net.xp.error._All",
"net.xp.event._All",
"net.xp.graphic._All",
"net.xp.log._All",
"net.xp.logic._All",
"net.xp.math._All",
"net.xp.net._All",
"net.xp.prototype._All",
"net.xp.str._All",
"net.xp.util._All"], {});